# Generated by Django 4.2.3 on 2023-07-13 17:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("filmesfav", "0003_ator_falecimento_diretor_falecimento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Filme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(help_text="Título do filme", max_length=280),
                ),
                ("sinopse", models.TextField(help_text="Sinopse")),
                (
                    "data",
                    models.DateField(
                        default=datetime.datetime(2023, 7, 13, 17, 44, 10, 491766),
                        help_text="Data de estreia",
                    ),
                ),
            ],
            options={"ordering": ["titulo", "data"],},
        ),
        migrations.AlterField(
            model_name="ator",
            name="falecimento",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(2023, 7, 13, 17, 44, 10, 492461),
                help_text="Data de falecimento (caso esteja vivo, deixe em branco).",
                null=True,
                verbose_name="Data de falecimento",
            ),
        ),
        migrations.AlterField(
            model_name="ator",
            name="nascimento",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 13, 17, 44, 10, 492457),
                help_text="Data de nascimento",
                verbose_name="Data de nascimento",
            ),
        ),
        migrations.AlterField(
            model_name="diretor",
            name="falecimento",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(2023, 7, 13, 17, 44, 10, 492329),
                help_text="Data de falecimento (caso esteja vivo, deixe em branco).",
                null=True,
                verbose_name="Data de falecimento",
            ),
        ),
        migrations.AlterField(
            model_name="diretor",
            name="nascimento",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 13, 17, 44, 10, 492324),
                help_text="Data de nascimento.",
                verbose_name="Data de nascimento",
            ),
        ),
        migrations.DeleteModel(name="Filmes",),
        migrations.AddField(
            model_name="filme",
            name="diretor",
            field=models.ForeignKey(
                help_text="Diretor",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="filmesfav.diretor",
            ),
        ),
        migrations.AddField(
            model_name="filme",
            name="elenco",
            field=models.ManyToManyField(
                help_text="Ator no elenco", to="filmesfav.ator"
            ),
        ),
        migrations.AddField(
            model_name="filme",
            name="genero",
            field=models.ManyToManyField(
                help_text="Generos do filme", to="filmesfav.genero"
            ),
        ),
    ]
