# Generated by Django 4.2.3 on 2023-07-13 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "filmesfav",
            "0004_filme_alter_ator_falecimento_alter_ator_nascimento_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ator",
            name="id_genero",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Feminino")],
                default="M",
                max_length=1,
                verbose_name="Identidade de gênero",
            ),
        ),
        migrations.AddField(
            model_name="diretor",
            name="id_genero",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Feminino")],
                default="M",
                max_length=1,
                verbose_name="Identidade de gênero",
            ),
        ),
        migrations.AlterField(
            model_name="ator",
            name="falecimento",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(2023, 7, 13, 17, 53, 57, 662926),
                help_text="Data de falecimento (caso esteja vivo, deixe em branco).",
                null=True,
                verbose_name="Data de falecimento",
            ),
        ),
        migrations.AlterField(
            model_name="ator",
            name="nascimento",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 13, 17, 53, 57, 662922),
                help_text="Data de nascimento",
                verbose_name="Data de nascimento",
            ),
        ),
        migrations.AlterField(
            model_name="diretor",
            name="falecimento",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(2023, 7, 13, 17, 53, 57, 662781),
                help_text="Data de falecimento (caso esteja vivo, deixe em branco).",
                null=True,
                verbose_name="Data de falecimento",
            ),
        ),
        migrations.AlterField(
            model_name="diretor",
            name="nascimento",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 13, 17, 53, 57, 662775),
                help_text="Data de nascimento.",
                verbose_name="Data de nascimento",
            ),
        ),
        migrations.AlterField(
            model_name="filme",
            name="data",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 13, 17, 53, 57, 662286),
                help_text="Data de estreia",
            ),
        ),
    ]
