# Generated by Django 4.2.3 on 2023-07-13 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filmesfav", "0005_ator_id_genero_diretor_id_genero_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ator",
            name="falecimento",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(2023, 7, 13, 17, 57, 21, 880971),
                help_text="Data de falecimento (caso esteja vivo, deixe em branco).",
                null=True,
                verbose_name="Data de falecimento",
            ),
        ),
        migrations.AlterField(
            model_name="ator",
            name="id_genero",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Feminino"), ("N", "Não-binário")],
                default="M",
                max_length=1,
                verbose_name="Identidade de gênero",
            ),
        ),
        migrations.AlterField(
            model_name="ator",
            name="nascimento",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 13, 17, 57, 21, 880967),
                help_text="Data de nascimento",
                verbose_name="Data de nascimento",
            ),
        ),
        migrations.AlterField(
            model_name="diretor",
            name="falecimento",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(2023, 7, 13, 17, 57, 21, 880821),
                help_text="Data de falecimento (caso esteja vivo, deixe em branco).",
                null=True,
                verbose_name="Data de falecimento",
            ),
        ),
        migrations.AlterField(
            model_name="diretor",
            name="id_genero",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Feminino"), ("N", "Não-binário")],
                default="M",
                max_length=1,
                verbose_name="Identidade de gênero",
            ),
        ),
        migrations.AlterField(
            model_name="diretor",
            name="nascimento",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 13, 17, 57, 21, 880815),
                help_text="Data de nascimento.",
                verbose_name="Data de nascimento",
            ),
        ),
        migrations.AlterField(
            model_name="filme",
            name="data",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 13, 17, 57, 21, 880239),
                help_text="Data de estreia",
            ),
        ),
    ]
