# Generated by Django 4.2.3 on 2023-07-13 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filmesfav", "0006_alter_ator_falecimento_alter_ator_id_genero_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ator",
            name="falecimento",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(2023, 7, 13, 18, 15, 54, 344193),
                help_text="Data de falecimento (caso esteja vivo, deixe em branco).",
                null=True,
                verbose_name="Data de falecimento",
            ),
        ),
        migrations.AlterField(
            model_name="ator",
            name="nascimento",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 13, 18, 15, 54, 344189),
                help_text="Data de nascimento",
                verbose_name="Data de nascimento",
            ),
        ),
        migrations.AlterField(
            model_name="diretor",
            name="falecimento",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(2023, 7, 13, 18, 15, 54, 344041),
                help_text="Data de falecimento (caso esteja vivo, deixe em branco).",
                null=True,
                verbose_name="Data de falecimento",
            ),
        ),
        migrations.AlterField(
            model_name="diretor",
            name="nascimento",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 13, 18, 15, 54, 344035),
                help_text="Data de nascimento.",
                verbose_name="Data de nascimento",
            ),
        ),
        migrations.AlterField(
            model_name="filme",
            name="data",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 13, 18, 15, 54, 343399),
                help_text="Data de estreia",
            ),
        ),
    ]
