# Generated by Django 4.2.3 on 2023-07-13 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filmesfav", "0007_alter_ator_falecimento_alter_ator_nascimento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ator",
            name="falecimento",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(2023, 7, 13, 18, 19, 2, 83087),
                help_text="Data de falecimento (caso esteja vivo, deixe em branco).",
                null=True,
                verbose_name="Data de falecimento",
            ),
        ),
        migrations.AlterField(
            model_name="ator",
            name="nascimento",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 13, 18, 19, 2, 83083),
                help_text="Data de nascimento",
                verbose_name="Data de nascimento",
            ),
        ),
        migrations.AlterField(
            model_name="diretor",
            name="falecimento",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(2023, 7, 13, 18, 19, 2, 82941),
                help_text="Data de falecimento (caso esteja vivo, deixe em branco).",
                null=True,
                verbose_name="Data de falecimento",
            ),
        ),
        migrations.AlterField(
            model_name="diretor",
            name="nascimento",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 13, 18, 19, 2, 82935),
                help_text="Data de nascimento.",
                verbose_name="Data de nascimento",
            ),
        ),
        migrations.AlterField(
            model_name="filme",
            name="data",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 13, 18, 19, 2, 82368),
                help_text="Data de estreia",
            ),
        ),
    ]
